
# Example config for dnsentinel

title = "TOML Example"

[appconfig]                             # Optional Section
logfile = "/var/log/dns-sentinel.log"   # Optional - Log path / file, this is the default value
loglevel = "info"                       # Optional - this is the default value
poll_interval = 1800                    # Optional - Time in seconds between runs, this is the default value

[provider.aws]                          # Optional Section - Only provider currently active
aws_access_key_id = ""                  # Optional - the AWS SDK in use will try to determine credentials (e.g. from ~/.aws/credentials)
aws_secret_access_key = ""              # Optional - same as above

[network]                               # Optional Section
type = "local"                          # Optional - accepted values are [ "local", "nat" ], default config is to use NAT Discovery
interface = "eth0"                      # Required if network.type = "local" - Not needed for network.type = "nat"

[zone]                                  # Required Section
name = "example.com"                    # Required - no default
record = "www.example.com"              # Required - no default
