
# Example config for dnsentinel

title = "TOML Example"

[appconfig]                             # Optional Section
logfile = "dns-sentinel.log"            # Optional - Log path / file, this is the default value
poll_interval = 1800                    # Optional - Time in seconds between runs, this is the default value

[network]                               # Optional Section
type = "local"                          # Optional - accepted values are [ "local", "nat" ], default config is to use NAT Discovery
interface = "eth0"                      # Required if network.type = "local" - Not needed for network.type = "nat"

[zone]                                  # Required
provider = "aws"                        # Required - aws is currently the only provider option
name = "example.com"                    # Required - no default
record = "www.example.com"              # Required - no default

[provider.aws]                          # Optional Section to declare an extra provider info
aws_access_key_id = ""                  # Optional - the AWS SDK in use will try to determine credentials (e.g. from ~/.aws/credentials)
aws_secret_access_key = ""              # Optional - same as above
