
# Test config for dnsentinel

title = "TOML Test"

[network]                             # Optional Section
type = "nat"                          # Optional - default config is to use NAT Discovery

[zone]                                # Required Section
name = "example.com"                  # Required - no default
record = "www.example.com"            # Required - no default
